---

- hosts: all
  become: true
  remote_user: root
  tasks:

  - name: install apache2
    apt:
      name: apache2
      state: latest  

  - name: php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
