
---

- hosts: all
  become: true
  remote_user: root
  pre_tasks: 
 
  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  remote_user: root
  tasks:


  - name: install apache and php for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache and php for centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  remote_user: root
  tasks:


  - name: install mariadb server on ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install mariadb on centos
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS" 



- hosts: file_servers
  become: true
  remote_user: root
  tasks:
 
  - name: install samba package
    package:
      name: samba
      state: latest
